### ISSUE TITLE
脚本跑的时候click位置有错误

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#10]
02/03/2016 14:22:45 INFO  - Click C:/Users/Administrator/Documents/GitHub/customer_side\images\homepage/xxx.png point: (425, 72)
02/03/2016 14:22:46 DEBUG - delay after click: 0.50s

我的屏幕分辨率是768*1024，我截得是从左到右的横屏图片，但是这个click的位置有点问题吧，中间位置是384，它为什么click的是425，感觉click的位置有问题啊。。纵坐标也是的，airtest click的是图片最中间的位置，x，y平均值的中间位置么？

**Comment by yisake** [comment]
有时候click的坐标是图片的右上角的坐标。。

**Comment by yisake** [comment]
在web工具上是没问题的，坐标是中间点的坐标，但是在脚本里面有时候就不正确了，有什么办法能debug吗？

**Comment by yisake** [comment]
手动试了下，同一张图片，在脚本里面的location和在cmd执行python脚本获得的居然不一致。。
脚本里面有appium，然后app在appium的class下面。appiumClient.app=airtest.connect(xxxx)，这种写法应该没问题吧，这是为什么。。。

**Comment by yisake** [comment]
脚本执行:
02/03/2016 18:16:00 DEBUG - Locate image path: C:/Users/Administrator/Documents/GitHub/customer_side\images\homepage/xxx.png
02/03/2016 18:16:00 DEBUG - start take snapshot(tmp\screen-160203181600-kpfs.png)
match-method: auto
02/03/2016 18:16:02 INFO  - CLICK (79, 57), timeout=20.00s, duration=None
02/03/2016 18:16:02 INFO  - Click (79, 57) point: (79, 57)

控制台执行：
>>> b=app.find('C:/Users/Administrator/Documents/GitHub/customer_side\images\homepage/xxx.png')
2016-02-03 18:23:06,315 - DEBUG: Locate image path: C:/Users/Administrator/Documents/GitHub/customer
_side\images\homepage/jianinghuayuan.png
2016-02-03 18:23:06,316 - DEBUG: start take snapshot(tmp\screen-160203182306-mspr.png)
match-method: auto
>>> b
(41, 104)

**Comment by codeskyblue** [comment]
图像识别已经独立出来了，你看看这个，看看有帮助没  <https://github.com/netease/aircv>

**Comment by codeskyblue** [comment]
点击位置不一样的问题，难道说背景图片长的不一样？

**Comment by codeskyblue** [comment]
手机的HOME键朝右呢？

**Comment by yisake** [comment]
就是同一张图片，运行命令行和执行脚本的时候定位的位置不一样，很匪夷所思。。

**Comment by yisake** [comment]
好像发现了点蛛丝马迹，image_match_method	'auto'			可以选择的有auto,template,sift，我用auto的时候，居然可以匹配到文字相同，但是颜色不同的两个位置，目前这个不像sikuli可以设置图像分辨的力度，就是相似度，这里面auto是不是相似度不高啊，只有0.7左右？其他的方法相似度是多少啊？

**Comment by yisake** [comment]
方便加个qq或者微信么？？

**Comment by yisake** [comment]
我看到一个threshold的app设置，这里面的设置用什么方法可以查看啊？是不是需要在调用前就设置好？

**Comment by yisake** [comment]
我设置了threshold为0.99,可是还是匹配到了错误的结果，只是文字一样，跟我预期的不一致，这个怎么解决。。

**Comment by yisake** [comment]
怪我看的不仔细，我把image_match_method='template'，然后设置threshold应该就没问题了~~
还有两个问题：
1.如何查看目前的全局设置globalSet
2.auto template sift，模板是全图匹配，sift是特征点，特征点可以设置threshold么？auto又是怎么样的？

**Comment by codeskyblue** [comment]
先把你的QQ发到我的 邮箱 codeskyblue at gmail  我随后加你QQ。 特征点我没有开发threshold的设置，因为并没有什么可以设置的值，你甚至不知道设置成多少才是合适的。 auto的意思是先进行模板匹配，匹配失败了，改成sift匹配。

我现在更倾向于使用模板匹配，因为准确率高，而且速度快。

**Comment by yisake** [comment]
我qq 840858160，平常基本用微信，也是这个号码，这个issue可以关了，是因为默认的threshold太低导致匹配不对，改了threshold之后就ok了。
