### ISSUE TITLE
请教一下并发多个设备进行测试的时候，好像会死掉。。。

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#11]
看了下报错，好像是在subprocess里面，通过adb命令操作什么。。。截图目前是通过adb去实现的吗？
同时进行多个设备的并发测试有没有遇到过什么问题？稳定性如何？

**Comment by codeskyblue** [comment]
我明天试试

**Comment by yisake** [comment]
我是开了两个模拟器，占用cpu比较高，可能导致adb不能正常work，还没有用真机测试过，两个真机同时执行脚本的话会不会出现错误？

**Comment by codeskyblue** [comment]
fixed in https://github.com/codeskyblue/AirtestX   测试过，似乎没什么问题
