### ISSUE TITLE
发现修改图片分辨率的方法可能有些问题(cv2.resize)

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#12]
看了下，项目中将图片分辨率做修改用了cv2.resize函数，用的是余数的宽高比，但是比配的图片阈值并不高，但是我百度了一下，
用了**nim = cv2.resize(imsrc, (**768,1280**), interpolation=cv2.INTER_CUBIC)**，直接带入，发现可以匹配到0.8以上阈值的图片，希望这部分能做下修改。: P

>>> imsrc = cv2.imread('s1080full.png',cv2.IMREAD_UNCHANGED)
>>> ow, oh = 768,1280
>>> cw, ch = 1080,1920
>>> (ratew, rateh) = cw/float(ow), ch/float(oh)
>>> nim = cv2.resize(imsrc, (0, 0), fx=ratew, fy=rateh)
>>>
>>> imsch = imread('B.png')
>>> result = find_all_template(nim, imsch)
templmatch_value(thresh:0.5) = 0.586
templmatch_value(thresh:0.5) = 0.574
templmatch_value(thresh:0.5) = 0.541
templmatch_value(thresh:0.5) = 0.532
templmatch_value(thresh:0.5) = 0.529
templmatch_value(thresh:0.5) = 0.524
templmatch_value(thresh:0.5) = 0.514
templmatch_value(thresh:0.5) = 0.504
templmatch_value(thresh:0.5) = 0.498

>>> imsrc = cv2.imread('s1080full.png',cv2.IMREAD_UNCHANGED)
>>> nim = cv2.resize(imsrc, (768,1280), interpolation=cv2.INTER_CUBIC)
>>>
>>> imsch = imread('B.png')
>>> result = find_all_template(nim, imsch)
templmatch_value(thresh:0.5) = 0.872
templmatch_value(thresh:0.5) = 0.743
templmatch_value(thresh:0.5) = 0.720
templmatch_value(thresh:0.5) = 0.666
templmatch_value(thresh:0.5) = 0.660
templmatch_value(thresh:0.5) = 0.657
templmatch_value(thresh:0.5) = 0.650
templmatch_value(thresh:0.5) = 0.643
templmatch_value(thresh:0.5) = 0.595
templmatch_value(thresh:0.5) = 0.593
templmatch_value(thresh:0.5) = 0.585
templmatch_value(thresh:0.5) = 0.581
templmatch_value(thresh:0.5) = 0.547
templmatch_value(thresh:0.5) = 0.524
templmatch_value(thresh:0.5) = 0.523
templmatch_value(thresh:0.5) = 0.519
templmatch_value(thresh:0.5) = 0.510
templmatch_value(thresh:0.5) = 0.508
templmatch_value(thresh:0.5) = 0.495

**Comment by yisake** [comment]
哈哈，可以把我加到contributer里面么? ~~

**Comment by codeskyblue** [comment]
你可以先提下pr，我来给你review下。非常欢迎

**Comment by codeskyblue** [comment]
等你写的多了，我就把你加到contributer里面

**Comment by yisake** [comment]
哈哈，开玩笑的，回到主题，这个问题你怎么看？是调用方法的问题还是？

**Comment by yisake** [comment]
sorry,可能是我使用的错误，目前resize的是目标图片，而不是当前设备的截图是吧？那是不是说，在高分辨率下的截图，可以在低分辨率的设备上以更高的阈值匹配到？

**Comment by codeskyblue** [comment]
fixed in https://github.com/codeskyblue/AirtestX
