### ISSUE TITLE
是不是必须初始化app才能用图片的方法，click，find等等。

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#5]
能不能让device这个类也可以直接截屏等操作，这样可以操作主页面等其他的情况。

**Comment by yisake** [comment]
sorry，我是用dir()方法查看device实例发现没有click等方法。但是其实还是可以调用的，这个原因是？

**Comment by codeskyblue** [comment]
必须先调用下 airtest.connect  确定连接哪个设备，不然 click 之类的是不确定操作哪台手机的

**Comment by yisake** [comment]
恩，好的，如何close这个问题？
