### ISSUE TITLE
dir()app实例的时候，发现没有click等方法。

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#6]
这是什么情况？？
>>> dir(app)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__',
 '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__seta
ttr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_clss', 'cron', 'logPerformance
', 'startMonitor', 'stopMonitor']
>>> app.click()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "airtest\devsuit.py", line 75, in _wrapper
    ret = v(*args, **kwargs)
TypeError: click() takes at least 2 arguments (1 given)

**Comment by yisake** [comment]
不能dir就不知道有哪些方法啊。。完全要看文档来用了。。。

**Comment by codeskyblue** [comment]
是的，这是一开始设计的缺陷导致的。后来也不是太好改了。

**Comment by yisake** [comment]
恩，除了API文档里面的方法还有哪些方法比较常用？

**Comment by yisake** [comment]
API文档会更新么~~

**Comment by yisake** [comment]
是不是因为没有写在class里面的缘故？都是函数？

**Comment by codeskyblue** [comment]
对差不多，用了写getattr, setattr之类的方法。

**Comment by codeskyblue** [comment]
fixed in https://github.com/codeskyblue/AirtestX
