### ISSUE TITLE
关于app的drag方法。

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#7]
drag是屏幕滑动的方法吗？如果是的话，在Genymotion模拟器不能滑动，一开始以为是两个图片的x坐标不一致，后来改成一致的x坐标，还是不行。

1.这个方法支持两个图片x或者y坐标不同的情况么？
2.是否是模拟器的原因，是驱动adb滑动屏幕？

**Comment by codeskyblue** [comment]
Genymotion 查了下好像是mac上的模拟器，就目前的实现看来，支持的应该不是很好

**Comment by yisake** [comment]
Genymotion windows也是可以的，我在用的就是windows版，那用什么模拟器比较稳定？sdk自带的太慢了，是不是推荐用真机？

**Comment by codeskyblue** [comment]
能不能提供个下载地址

**Comment by yisake** [comment]
Genymotion主程序：https://yunpan.cn/crSDGJPfad5jI （提取码：827a）

ova虚拟机文件：https://yunpan.cn/crSD97JBkRivt （提取码：11e0）

**Comment by yisake** [comment]
drag这个方法是通过adb去滑动的吗？

**Comment by codeskyblue** [comment]
新项目 https://github.com/codeskyblue/AirtestX中的drag使用了 uiautomator去做  （for android)
