### ISSUE TITLE
adb keyboard好像跟appium的键盘冲突了。。。

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#8]
如题，键盘有没有方法能切换？到设置里面切换键盘？

**Comment by codeskyblue** [comment]
appium的键盘是不是可以通过adb的广播来输入

**Comment by codeskyblue** [comment]
@yisake 有没有解决办法？

**Comment by yisake** [comment]
![image](https://cloud.githubusercontent.com/assets/4221944/12602322/57a95772-c4e3-11e5-9b6b-65641a7aa307.png)

放了张截图，airtest用的是不是图片里面的ADB Keyboard？
目前看来可能需要切换吧，或者只用一种输入法，appium的键盘其实还好，可以输中文什么的。

**Comment by yisake** [comment]
网易这边是不是airtest和appium结合使用的？

**Comment by codeskyblue** [comment]
appium的输入法，能不能通过adb的广播去控制 @yisake

**Comment by codeskyblue** [comment]
atx已放弃使用adb-keyboard.apk
