### ISSUE TITLE
截图工具不能保存中文名

### ISSUE THREAD

**Issue by yisake** [NetEase/airtest#9]
web的截图工具不能保存成中文名啊。。
>_<

**Comment by codeskyblue** [comment]
不好意思，因为这个库已经好久不维护，我不知道该怎么回答你。但看到你这么热情，感觉这个项目是由重新启动的必要了，Thanks. Issue直接修复之后才会被关闭。

**Comment by yisake** [comment]
恩，哈哈，手机端测试工具目前也就那么些了，估计不会有什么更好的了，我在用appium，但是遇到了控件不能识别的问题，在51testing看到这个工具的，跟sikuli工作原理一致，在自动化中是能起到作用的，用来操作控件，或者用来验证ui界面的展示，我觉得这个工具还是有维持下去的理由~~

**Comment by codeskyblue** [comment]
嗯，现在已经计划去弄了。项目慢慢的重启了

**Comment by codeskyblue** [comment]
目前依然还是个问题，没有修复

**Comment by codeskyblue** [comment]
fixed in https://github.com/codeskyblue/AirtestX
